=== uib-ub/fumadocs-menota/public/handbook/v3/samples/menotaBliX.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
	attributeFormDefault="unqualified">
	<xs:element name="transcription">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="text" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType mixed="true">
						<xs:sequence minOccurs="0" maxOccurs="unbounded">
							<xs:group ref="Breaks" minOccurs="0"/>
							<xs:element name="div" type="Div" minOccurs="0"/>
							<xs:element name="num" type="Numeral" minOccurs="0"/>
							<xs:element name="add" type="Addition" minOccurs="0"/>
							<xs:element name="del" type="Deletion" minOccurs="0"/>
							<xs:element name="supplied" type="Suppletion" minOccurs="0"/>
							<xs:element name="unclear" type="Unclear" minOccurs="0"/>
							<xs:element name="choice" type="Choice" minOccurs="0"/>
							<xs:element name="c" type="Character" minOccurs="0"/>
							<xs:element name="gap" type="Gap" minOccurs="0"/>
							<xs:element name="surplus" type="Surplus" minOccurs="0"/>
							<xs:element name="suppressed" type="Suppressed" minOccurs="0"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Div">
		<xs:sequence>
			<xs:element name="head" type="Paragraph" minOccurs="0" maxOccurs="1"/>
			<xs:group ref="Breaks" minOccurs="0" maxOccurs="unbounded"/>
			<xs:choice>
				<xs:sequence minOccurs="1" maxOccurs="unbounded">
					<xs:element name="div" type="Div" minOccurs="1" maxOccurs="1"/>
					<xs:group ref="Breaks" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:sequence minOccurs="1" maxOccurs="unbounded">
					<xs:element name="p" type="Paragraph" minOccurs="1" maxOccurs="1"/>
					<xs:group ref="Breaks" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="type" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="text"/>
					<xs:enumeration value="chapter"/>
					<xs:enumeration value="reply"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="subtype">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="saga"/>
					<xs:enumeration value="dialogue"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="n">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="\d+"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="Paragraph" mixed="true">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:group ref="Breaks" minOccurs="0"/>
			<xs:element name="num" type="Numeral" minOccurs="0"/>
			<xs:element name="add" type="Addition" minOccurs="0"/>
			<xs:element name="del" type="Deletion" minOccurs="0"/>
			<xs:element name="supplied" type="Suppletion" minOccurs="0"/>
			<xs:element name="unclear" type="Unclear" minOccurs="0"/>
			<xs:element name="choice" type="Choice" minOccurs="0"/>
			<xs:element name="c" type="Character" minOccurs="0"/>
			<xs:element name="gap" type="Gap" minOccurs="0"/>
			<xs:element name="surplus" type="Surplus" minOccurs="0"/>
			<xs:element name="suppressed" type="Suppressed" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:group name="Breaks">
		<xs:sequence>
			<xs:element name="pb" type="PageBreak" minOccurs="0" maxOccurs="1"/>
			<xs:element name="cb" type="ColBreak" minOccurs="0" maxOccurs="1"/>
			<xs:element name="lb" type="LineBreak" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:group>
	<xs:complexType name="PageBreak">
		<xs:attribute name="n">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="\d+[prv]"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="ColBreak">
		<xs:attribute name="n">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="[ab]"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="LineBreak">
		<xs:attribute name="n">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="\d+"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="rend">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="\d"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="Numeral" mixed="true">
		<xs:attribute name="type">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="cardinal"/>
					<xs:enumeration value="ordinal"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="value" type="xs:int"/>
	</xs:complexType>
	<xs:complexType name="Addition" mixed="true">
		<xs:sequence minOccurs="0">
			<xs:element name="unclear" type="Unclear"/>
		</xs:sequence>
		<xs:attribute name="place">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="supralinear"/>
					<xs:enumeration value="margin"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="Deletion" mixed="true">
		<xs:sequence minOccurs="0">
			<xs:element name="num" type="Numeral"/>
		</xs:sequence>
		<xs:attribute name="rend">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="erasure"/>
					<xs:enumeration value="subpunction"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="type">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="expunction"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="Suppletion" mixed="true">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="c" type="Character" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="reason">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="missing"/>
					<xs:enumeration value="damage"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="Unclear" mixed="true">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="num" type="Numeral" minOccurs="0"/>
			<xs:element name="supplied" type="Suppletion" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="width" type="xs:int"/>
	</xs:complexType>
	<xs:complexType name="Choice">
		<xs:sequence minOccurs="1" maxOccurs="1">
			<xs:element name="sic" type="Sic"/>
			<xs:element name="corr" type="Corr"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Sic" mixed="true"/>
	<xs:complexType name="Corr" mixed="true"/>
	<xs:complexType name="Character" mixed="true">
		<xs:attribute name="type">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="initial"/>
					<xs:enumeration value="littNot"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="Gap"/>
	<xs:complexType name="Surplus" mixed="true"/>
	<xs:complexType name="Suppressed" mixed="true"/>
</xs:schema>

=== uib-ub/fumadocs-menota/legacy/handbok/v3/documents/samples/AM-619-4to-57v.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE transcription [
   <!ENTITY % menotaEntities SYSTEM
      'http://www.menota.org/menota-entities.txt'>
   %menotaEntities;
]>
<transcription 
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="http://folk.uib.no/rpa021/emroon/v2-0-6/workbench/menotaBliX.xsd">
   <text>
      <div type="text">
         <div type="chapter">
            <head>
               :57v:
               :6:
               <num type="cardinal" value="5">.v.</num>
            </head>
            <p>
               :7: <c type="initial">S</c>væini æinu(m) saclausum var þungr gløpr kendr. (oc) galt h(ann)
               :8: í þvi annars ma(n)nz sem margtít er. (oc) r&aeligacute;nto þæir h(ann)
               tun-:9:gu (oc) male sinu.
            </p>
            <p>
               <c type="litNot">N</c>u hafðe h(ann) fregit (oc) spurt til miscu(n)nar
               :10: (oc) iartegna oláfs hins hælga k(onong)s. (oc) fystizc h(ann) þingat at fara
               :11: (oc) læíta sér miscunar við þa(n)n guðs ast_vín.
            </p>
            <p>
               <c type="litNot">H</c>æiman fór h(ann) (oc) co(m) þi(n)gat
               :12: til þes dyrlega staðar er h(ann) hvilir át. (oc) vacte þar iðulega (oc) bað bønu(m)
               :13: sinum. hét á h(ann) til hialpa. (oc) miscu(n)nar. bað í guðs nafne léa sér+mals
               :14: (oc) hæilsu er h(ann) hafðe mist fyrir+utan sin tilv&eogon;rca.
            </p>
            <p>
               <c type="litNot">N</c>u á stund nocorre
               :15: um dag æin þa sofnaðe h(ann) í kirkiu ínni. (oc) syndisc h&aolig;nu(m) i søfne (maðr)
               :16: ein æinca_friðr (oc) æigi al+hór at vexti ganga til sín ut ór scrinino. (oc)
               :17: toc hendi sinni í mun h&aolig;nu(m) (oc) hæimti til sin þa(n)n litla stuf er eptir
               :18: stoð tungu(n)nar. (oc) togaðe sva hart (oc) tøygði at sá+ungi (maðr) fec æigi þolat
               :19: í søfneno(m) u_øpande.
            </p>
            <p>
               <c type="litNot">Ð</c>vi næst vacnaðe h(ann) (oc) ræis upp hæil (oc) þaccaðe
               v&aolig;-:20:rum drotne fegin_samlega (oc) þæim guðs vín er h(ann) hafðe hæilsu (oc)
               mis-:21:cun af þeget. faret þangat aðr mallaus (oc) sot h(an)s hælga scrin. (oc) for
               :22: þaðan hæil (oc) scoren_orðr til síns hæimilis.
            </p>
         </div>
      </div>
   </text>
</transcription>
